name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Copy CNAME to deploy folder
        run: cp CNAME datemarket_v5/CNAME
      - uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_TOKEN }}
          enablement: true
      - uses: actions/upload-pages-artifact@v5
        with:
          path: datemarket_v5
      - uses: actions/deploy-pages@v4
